spring:
    application:
        name: activiti-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
server:
    port: 32106
eureka:
    instance:
      prefer-ip-address: true

ht.config.ui:
  gatewayUrl: http://172.16.200.110:30111/
  changePwdUrl: http://172.16.200.110:30131/html/user/changePwdOther.html
  userInfoUpdate: http://172.16.200.110:30131/html/user/userInfoOther.html
